package win.catgo.gpt.network

import kotlinx.serialization.json.*
import org.junit.Assert.*
import org.junit.Test

/** Snapshots generated by scripts/hermes-prompt-fixture.py with real prompt_toolkit rendering. */
class HermesRenderedPromptTest {
    private val fixtures = Json.parseToJsonElement(javaClass.getResource("/hermes-prompt-vt.json")!!.readText()).jsonObject

    @Test fun realRendererChineseQuestionAndIncrementalRedrawAreParsed() {
        val snapshots = fixtures.getValue("question").jsonArray.map { it.jsonPrimitive.content }
        val screen = TerminalTextScreen()
        screen.append(snapshots[0].toByteArray())
        val first = HermesPromptParser.parse(screen.lines())!!
        assertTrue(first.complete)
        assertEquals("请问部署到哪里？", first.body)
        screen.append(snapshots[1].removePrefix(snapshots[0]).toByteArray())
        val next = HermesPromptParser.parse(screen.lines())!!
        assertTrue(next.complete)
        assertEquals("请问使用哪个环境？", next.body)
        assertEquals(listOf("1", "2", "3"), next.choices.map { it.key })
    }

    @Test fun realRendererApprovalAndSecretRemainCompleteUnderByteFragmentation() {
        for (name in listOf("approval", "secret")) {
            val raw = fixtures.getValue(name).jsonArray[0].jsonPrimitive.content
            val screen = TerminalTextScreen()
            raw.toByteArray().forEach { screen.append(byteArrayOf(it)) }
            val prompt = HermesPromptParser.parse(screen.lines())!!
            assertTrue(name, prompt.complete)
            if (name == "approval") assertEquals("sudo systemctl status hermes", prompt.body)
            else assertEquals(HermesInteractionKind.SECRET, prompt.kind)
        }
    }
}
